server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-security-demo
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

